---
# tasks file for webgme

- set_fact:
    user_home: "/home/{{ ansible_user }}"
    curr_user: "{{ ansible_user }}"

- set_fact:
    node_path: "{{ user_home }}/.nvm/versions/node/v{{ webgme_node_version }}"
    ssh_dir: "{{ user_home }}/.ssh"
    webgme_local_path: "{{ user_home }}/{{ webgme_app_name }}"

- set_fact:
    node_bin: "{{ node_path }}/bin"
    node_env_path: "{{ node_path }}/bin:{{ ansible_env.PATH }}"
    node_modules_global: "{{ node_path }}/lib/node_modules"
    git_repo_keyfile_remote: "{{ ssh_dir }}/git_keyfile"


# >> npm ansible module fails since version 2.0.2 <<
# - name: "Install pm2 globally"
#   become: yes
#   npm:
#     name: "{{ item }}"
#     executable: "{{ npm_executable }}"
#     global: yes
#     production: yes
#   with_items:
#     - pm2
#     - npm-install-peers
#     - bower

- name: "Install pm2, bower and npm-install-peers globally"
  command: "npm install -g pm2 npm-install-peers bower"
  environment:
    PATH: "{{ node_env_path }}"

################################################################################
# this part only needed if git repo is private
###
- name: "Copy git.sh"
  copy:
    src: "git.sh"
    dest: "{{ ssh_dir }}/git.sh"
    mode: 0744
  when: "{{ webgme_flavor.git_repo_key is defined }}"

- name: "Copy keyfile for git repo"
  copy:
    src: "{{ webgme_flavor.git_repo_key }}"
    dest: "{{ git_repo_keyfile_remote }}"
    mode: 0600
  when: "{{ webgme_flavor.git_repo_key is defined }}"

- name: "Clone webgme flavor git repo with key"
  git:
    repo: "{{ webgme_flavor.git_repo_url }}"
    version: "{{ webgme_flavor.git_repo_branch }}"
    dest: "{{ webgme_local_path }}"
    key_file: "{{ git_repo_keyfile_remote }}"
    accept_hostkey: yes
    update: yes
    force: yes
  environment:
    GIT_SSH: "{{ ssh_dir }}/git.sh"
    PKEY: "{{ git_repo_keyfile_remote }}"
  when: "{{ webgme_flavor.git_repo_key is defined }}"
###
# -
################################################################################

- name: "Clone webgme flavor git repo - no key"
  git:
    repo: "{{ webgme_flavor.git_repo_url }}"
    version: "{{ webgme_flavor.git_repo_branch }}"
    dest: "{{ webgme_local_path }}"
    accept_hostkey: yes
    update: yes
    force: yes
  when: "{{ webgme_flavor.git_repo_key is not defined }}"

# >> npm ansible module fails since version 2.0.2 <<
# - name: "Install npm packages in cloned folder based on package.json"
#   npm:
#     executable: "{{ npm_executable }}"
#     path: "{{ webgme_local_path }}"
- name: "Install npm packages in cloned folder based on package.json"
  command: "npm install"
  args:
    chdir: "{{ webgme_local_path }}"
  environment:
    PATH: "{{ node_env_path }}"

- name: "Install peer dependencies"
  command: "npm-install-peers"
  args:
    chdir: "{{ webgme_local_path }}"
  environment:
    PATH: "{{ node_env_path }}"

- name: "Copy node-app.json to root"
  template:
    src: node-app.json.j2
    dest: "{{ user_home }}/node-app.json"

- name: "Stop app"
  command: "pm2 stop node-app.json"
  args:
    chdir: "{{ webgme_local_path }}"
  environment:
    PATH: "{{ node_env_path }}"
  ignore_errors: yes

- name: "Start app"
  command: "pm2 start node-app.json"
  args:
    chdir: "{{ user_home }}"
  environment:
    PATH: "{{ node_env_path }}"

- name: "Ensure pm2 starts when vm restarts"
  become: yes
  command: "env PATH=$PATH:{{ node_bin }} {{ node_modules_global }}/pm2/bin/pm2 startup -u {{ curr_user }}"
